version: "3"
services:

  db:
    image: mariadb:10.2.10
    # 윈도우에서 빌드시 my.cnf 파일 퍼미션 -rwxr-xr-x 일괄 설정 문제로 MariaDB에서
    # "World-writable config file '/etc/mysql/conf.d/my.cnf' is ignored" 되서 데이터 삽입시 한글 깨져서 입력되고 길이제한 걸리기도 하는 문제 수정용
    command: [
        '--character-set-server=utf8mb4',
        '--skip-character-set-client-handshake',
        '--collation-server=utf8mb4_unicode_ci',
    ]   
    container_name: app_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./back/.env.example
    environment:
      TZ: Asia/Seoul
    networks:
      - backnet
      
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./back
    ports: 
      - "5000:5000"
    container_name: app_backend
    volumes:
      - ./back:/app
    environment:
      FLASK_ENV: development
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
        

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./front:/app
    networks:
      - frontnet
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app_nginx
    ports: 
      - "4000:80"
    depends_on: 
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
