version: "3"
services:

  db:
    image: mariadb:10.2.10
    container_name: app_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backnet
      
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./back
    ports: 
      - "5000:5000"
    container_name: app_backend
    volumes:
      - ./back:/app
    environment:
      FLASK_ENV: development
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
        

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./front:/app
    networks:
      - frontnet
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: app_nginx
    ports: 
      - "4000:80"
    depends_on: 
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
